# PyPhi configuration
# ~~~~~~~~~~~~~~~~~~~
# See the documentation for ``pyphi.config`` for more info.
---
# Approximations and theoretical options
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The version of the theory to use
IIT_VERSION: 3
# In certain cases, making a cut can actually cause a previously reducible
# concept to become a proper, irreducible concept. Assuming this can never
# happen can increase performance significantly, however the obtained results
# are not strictly accurate.
ASSUME_CUTS_CANNOT_CREATE_NEW_CONCEPTS: false
# The measure to use when computing phi ("EMD", "KLD", "L1", ...)
REPERTOIRE_DISTANCE: "EMD"
# The measure to use when computing big-phi.
CES_DISTANCE: "EMD"
# The measure to use when computing actual causation alpha values.
ACTUAL_CAUSATION_MEASURE: "PMI"
# Controls the partitioning scheme for distinctions.
PARTITION_TYPE: "BI"
# The type of system cuts to use.
SYSTEM_PARTITION_TYPE: "DIRECTED_BI"
# The type of system cuts to use.
SYSTEM_CUTS: "3.0_STYLE"
# Controls how ties among MICE are broken.
MICE_TIE_RESOLUTION: "LARGEST_PURVIEW"
# In some applications of this library, you may want to allow single
# micro-nodes with a self-loop to have nonzero Phi. See ``pyphi.config`` for
# details.
SINGLE_MICRO_NODES_WITH_SELFLOOPS_HAVE_PHI: false
# Controls whether a subsystem's state is validated when the subsystem is
# created.
VALIDATE_SUBSYSTEM_STATES: true
# Controls whether a system is validated for conditional independence.
VALIDATE_CONDITIONAL_INDEPENDENCE: true

# Parallelization and system resources
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Controls whether concepts are evaluated in parallel.
PARALLEL_CONCEPT_EVALUATION: false
# Controls whether cuts are evaluated in parallel, which requires more memory.
# If cuts are evaluated sequentially, only two SIAs need to be in memory at a
# time.
PARALLEL_CUT_EVALUATION: false
# Controls whether complexes are evaluated in parallel.
PARALLEL_COMPLEX_EVALUATION: false
# The number of CPU cores to use in parallel.
# -1 means all available cores, -2 means all but one available cores, etc.
NUMBER_OF_CORES: -1
# Some functions are memoized using an in-memory cache. This is the maximum
# percentage of memory that these caches can collectively use.
MAXIMUM_CACHE_MEMORY_PERCENTAGE: 100
# Arguments to `ray.init()`
RAY_CONFIG:
  address: "auto"

# Memoization and caching
# ~~~~~~~~~~~~~~~~~~~~~~~
# Controls whether cause and effect repertoires are cached.
CACHE_REPERTOIRES: true
# Controls whether the potential purviews of the mechanisms of a network are
# cached. Speeds up calculations when the same network is used repeatedly, but
# takes up additional memory, and makes network initialization slow.
CACHE_POTENTIAL_PURVIEWS: true
# Controls whether subsystem caches are automatically cleared after computing
# the SIA for the subsystem.
CLEAR_SUBSYSTEM_CACHES_AFTER_COMPUTING_SIA: false
# Use a Redis server as a MICE cache
REDIS_CACHE: false
# Redis connection configuration
REDIS_CONFIG:
  host: "localhost"
  port: 6379
  db: 0
  test_db: 1

# Logging
# ~~~~~~~
# Whether to suppress the welcome message.
WELCOME_OFF: false
# The log level to write to stdout.
LOG_STDOUT_LEVEL: "WARNING"
# The log level to write to `LOG_FILE`.
LOG_FILE_LEVEL: "INFO"
# The file to log to.
LOG_FILE: "pyphi.log"
# Enable/disable progress bars
PROGRESS_BARS: true
# Use pretty __str__-like formatting in repr calls.
REPR_VERBOSITY: 2
# Print numbers as fractions if the denominator isn't too big.
PRINT_FRACTIONS: true

# Numerical precision
# ~~~~~~~~~~~~~~~~~~~
# The number of decimal places to which Phi values are considered accurate.
PRECISION: 6
